# Generated by Django 4.1.7 on 2023-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name_movie',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
