# Generated by Django 4.1.7 on 2023-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_name_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budged',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
