# Generated by Django 4.1.7 on 2023-02-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='artist',
            field=models.ManyToManyField(to='movie_app.artist'),
        ),
    ]
