# Generated by Django 4.1.7 on 2023-02-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_movie_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='email',
        ),
    ]
