# Generated by Django 4.1.7 on 2023-03-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_genre_alter_movie_artist_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=' ', upload_to='uploads/movie_image'),
        ),
    ]
