# Generated by Django 4.1.7 on 2023-03-14 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=' ', upload_to='trailer_movie/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(blank=' ', upload_to='movie_image/'),
        ),
    ]
