# Generated by Django 4.1.7 on 2023-03-14 09:39

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_movie_trailer_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
