# Generated by Django 4.1.7 on 2023-03-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_remove_feedback_name_remove_feedback_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
