# Generated by Django 4.1.7 on 2023-03-14 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0022_rename_movie_id_feedback_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
