# Generated by Django 4.1.7 on 2023-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0024_alter_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('€', '€'), ('₽', '₽')], default='R', max_length=3),
        ),
    ]
